minor2/home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views


app_name = 'home'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^essaysuc/$',views.essaysuc,name='essaysuc'),

]

minor2/minor2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('home.urls')),
]

minor2/templates/aj.html
<html>

   <head>
      <title>The jQuery Example</title>
      <script type = "text/javascript" 
         src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		
      <script type = "text/javascript" language = "javascript">
         $(document).ready(function() {
            $("#driver").click(function(event){
               $('#stage').load('test.html');
            });
         });
      </script>
   </head>
	
   <body>
	
      <p>Click on the button to load /jquery/result.html file −</p>
		
      <div id = "stage" style = "background-color:cc0;">
         STAGE
      </div>
		
      <input type = "button" id = "driver" value = "Load Data" />
		
   </body>
	
</html>

minor2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'home/index.css' %}" media="all" />
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Lobster" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="header" style="margin-top: -18px;height: 140px;">

            </div>

    </div>

      &nbsp;
    &nbsp;
           <div class="row" style="z-index: 1900;">
               <div class="col-md-6" style="z-index:1900;">
                   <div class="container-fluid">
                   <div class="section">
        <div class="left" style="width: 100%;z-index: 1900;">
            <img src="{% static 'home/images/zeimusu-Thumbtack-note-blank.png' %}" style="margin-top:-140px;width:300px;height: 200px;z-index: 2000;">

         <h1 style="transform:rotateZ(-10deg);margin-top:-170px;margin-left:15px;padding-left:50px;z-index:2100;font-family: 'Lobster', cursive;font-size:50px;">GetEssay</h1>
<img src="{% static 'home/images/icon-content-1.png' %}" style="margin-top:100px;width:200px;height: 200px;z-index: 2000;">
            <h2 style="margin-top:-120px;padding-left:250px;font-family: 'Permanent Marker', cursive;font-size: 40px;">Get any type of essays you need..!!</h2>
             <h2 style="margin-top:150px;padding-left:50px;font-family: 'Permanent Marker', cursive;font-size: 40px;">In No Time..!!</h2>
          <img src="{% static 'home/images/time.png' %}" style="margin-top:-120px;margin-left:350px;width:200px;height: 200px;z-index: 2000;">

        </div>

        </div>
                   </div>
               </div>
               <div class="col-md-6">
                   <div class="left" style="width: 100%;" >
                       &nbsp;
                       &nbsp;
                       <div class="row" style="padding-left: 30px;padding-right: 30px;">
                           <br>
                           <br>
                           <br>
                           <form action="{% url 'home:essaysuc'%}#result" method="post">
					     {% csrf_token %}
                             {{ form }}

                           <br>
                               <br>
                               <br>

                   <button style="margin-left: 220px;" type="submit" class="btn btn-primary">Go..</button>
                   </form>
                       </div>

        </div>
               </div>
           </div>

    <div class="row">

        <div class="col-md-3">

        </div>
        <div class="col-md-6" style="padding-bottom: 25px">
            <div id="result" class="left" style="width: 100%;overflow: auto;overflow-x: hidden;text-align: center;  " >
                       &nbsp;
                       &nbsp;
                <h2 style="font-family: 'Permanent Marker', cursive;font-size: 40px;text-align: center;">Essay</h2>
                       <div class="row" style="padding-left: 30px;padding-right: 30px;">
                           <br>
                           <br>
                           <br>{{ essay }}

                       </div>

        </div>
        </div>
        <div class="col-md-3">

        </div>

    </div>





       </div>




</body>
</html>

minor2/templates/success.html
<!DOCTYPE html>
<html>
<body>

<div id="demo">
<h1>The XMLHttpRequest Object</h1>
<button type="button" onclick="loadDoc()">Change Content</button>
</div>

<script>
function loadDoc() {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("demo").innerHTML =
      this.responseText;
    }
  };
  xhttp.open("GET", "uj.txt", true);
  xhttp.send();
}
</script>

</body>
</html>

minor2/templates/test.html
<!DOCTYPE html>
<html> 
<head> 
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 
  <title>Google Maps Multiple Markers</title> 
  <script src="http://maps.google.com/maps/api/js?sensor=false" 
          type="text/javascript"></script>
</head> 
<body>
  <div id="map" style="width: 500px; height: 400px;"></div>

  <script type="text/javascript">
    var locations = [
	['jaypee',28.6292476,77.3714064, 3],
      ['expo',28.6306413,77.3733375, 2],
      ['Shipra',28.6342574,77.3699901, 1]
    ];

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 13,
      center: new google.maps.LatLng(28.6313821,77.36),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>
</body>
</html>